### ISSUE TITLE
QI-Core 4.1.1 CommunicationNotDone Reason Code Mapping

### ISSUE THREAD

**Issue by jkotanchik-SB** [cqframework/clinical_quality_language#1153]
Similar to #1136, there is an issue in how reasonCode is getting mapped to ELM for the CommunicationNotDone datatype in QI-Core 4.1.1.

Test Measure:
[BM1420-v0.0.000-FHIR4.zip](https://github.com/cqframework/clinical_quality_language/files/11235221/BM1420-v0.0.000-FHIR4.zip)

Generated ELM:
[elm.txt](https://github.com/cqframework/clinical_quality_language/files/11235235/elm.txt)

**Comment by brynrhodes** [comment]
The underlying issue is that the negation pattern relies on the "what is being negated" element having a max cardinality of 1. It's not clear whether or how the negation pattern could be generalized to multi-cardinality elements. Compounding the issue in this case is that although the profiles for Communication and CommunicationNotDone in QICore do reduce the cardinality to a max of 1, because the underlying element is still multi-cardinality the mapping does not expand correctly. In addition, the primary code path for Communication and CommunicationNotDone has been changed in QICore 5 to the single-cardinality element topic. For these reasons, we recommend not addressing this issue in the translator/mapping but rather avoiding the use of the reasonCode element directly in the negation pattern for CommunicationNotDone. We have updated the pattern here to reflect this recommendation: https://github.com/cqframework/CQL-Formatting-and-Usage-Wiki/wiki/Authoring-Patterns---QICore-v4.1.1#communication-not-done

**Comment by kimberlysmuk** [comment]
To summarize: 
1) MDs should avoid using 'reasonCode' for the time being - follow new authoring pattern.
2) QI-Core will be updated to allow .... can you explain in basic terms what the update would be? and when this update to QI-Core would happen? 
3) the execution engine will need to be updated. Is this update to accomodate the workaround or future QI-Core changes? Can you explain what the execution engine update will address?

**Comment by brynrhodes** [comment]
Regarding the QICore update, QICore 5 has addressed this issue by changing CommunicationNotDone primary code path to topic. QICore 5 is published, but movement to that is subject to overall timeline.

**Comment by jenseeman** [comment]
Closing this issue per discussion on the 6/27/23 FHIR measure collab call. Future work to be done in https://github.com/cqframework/cql-execution/issues/296
