### ISSUE TITLE
Processor returns values for DataEntries that have no values

### ISSUE THREAD

**Issue by mcmcphillips** [cqframework/clinical_quality_language#1156]
https://oncprojectracking.healthit.gov/support/browse/BONNIEMAT-1428

@brynrhodes

In Madie we are able to perceive issues with data entries being returned with no values. We can check this by

`    log.info(
        "FHIR CONTEXT IS {}",
        fhirContext
            .newJsonParser()
            .setPrettyPrint(true)
            .encodeResourceToString(r4EffectiveDataRequirements));`
            
  This displays multiple entries without values
  
  `  }, {
    "profile": [ "http://hl7.org/fhir/ReferenceVersionRules" ],
    "mustSupport": [ "value" ]
  }, {
    "profile": [ "http://hl7.org/fhir/ReferredDocumentStatus" ],
    "mustSupport": [ "value" ]
  }, {
    "profile": [ "http://hl7.org/fhir/RelatedArtifactType" ],
    "mustSupport": [ "value" ]
  }, {`
  
  These additional values lead to multiple export lines with emp[ty values as displayed in BONNIEMAT-1428

**Comment by JSRankins** [comment]
@brynrhodes, I think the issue is that Data Requirements Processor seems to provide all data requirements back from included libraries, even if they were not used in the primary library. Not saying that is the wrong design. But we are using Data Requirements Processor to do the type conversion between QI-Core and FHIR. As part of that process, is there something in the src code to tease out the data requirements that are not directly or indirectly used by the main library?

**Comment by brynrhodes** [comment]
Yes, the dataRequirementsProcessor takes an optional parameter that indicates which expressions in the Library should be considered. In that case, only items that are referenced by the given expressions will be considered. For use in measures, this means the top-level expressions referenced by the measure should be given. I've added test cases for the CMS143 and CMS149 measure content in the linked bonnie ticket to confirm effective data requirements calculation.

**Comment by brynrhodes** [comment]
Included in 2.11.0
