### ISSUE TITLE
List-valued expression was demoted to a singleton

### ISSUE THREAD

**Issue by cmoesel** [cqframework/clinical_quality_language#120]
Given the following CQL:
```
library Test version '1'
using QUICK
valueset "Ambulatory/ED Visit": '2.16.840.1.113883.3.464.1003.101.12.1061'
context Patient
define Visits: [Encounter: "Ambulatory/ED Visit"]
```
The CQL-to-ELM translator produces this warning:
```
Warning:[n/a] List-valued expression was demoted to a singleton.
```
Or in the generated XML:
```xml
<annotation message="List-valued expression was demoted to a singleton."
            errorType="semantic" 
            errorSeverity="warning" 
            xsi:type="a:CqlToElmError"/>
```

I don't see anything in the CQL that would necessitate a demotion to a singleton.  The ELM XML does ensure `Patient` is a singleton, but this is normal and expected behavior.  In addition, if I make the `Foo` expression evaluate to a literal (e.g., `true`) instead of the `Retrieve`, the warning goes away.

**Comment by brynrhodes** [comment]
The reason this happens with the QUICK model specifically is that the "type" element of Encounter is actually a List<Concept>, not a single Concept. One of the things I added in the latest round was validation on the retrieve target, and it validates by running an "in" on the code path and the retrieve target expression. The warning is indicating that the "type" element will need to be demoted to a singleton in order to evaluate.

**Comment by cmoesel** [comment]
Ah... OK.  That makes sense.  Thanks for the explanation.
