### ISSUE TITLE
Incorrect result for TestIntersectNull

### ISSUE THREAD

**Issue by brynrhodes** [cqframework/clinical_quality_language#1343]
The TestIntersectNull test is:

```
Interval[1, 10] intersect Interval[5, null)
```

According to the spec, the expected outcome should be `Interval[5, null)`

However, the Java engine test suite had this expected outcome as null. In addition, there are 4 tests related to this in the published spec (TestIntersectNull1 through TestIntersectNull4) that were not in the Java engine test suite. I've added the correct expected outcome to the test suite, as well as the missing tests, but the engine now does not pass these tests (so they've been added to the skip list).

**Comment by holly-smile** [comment]
I can't seem to find where in the spec it is stated that the expected outcome here is `Interval[5, null)` and not just `null`. The [documentation](https://cql.hl7.org/09-b-cqlreference.html#intersect-1) for "Intersect" doesn't say anything about this, only that it returns `null` if one of the arguments is `null` instead of an Interval.

Under the hood, evaluation of `Intersect` uses the same logic as the `Greater` and `Less` operators (or `SameOrBefore` or `LessOrEqual` when evaluating the overlap) to compare the ends of the intervals, all of which evaluate to `null` if one of the ends are null.

**Comment by cmoesel** [comment]
The spec says this:
> The intersect operator for intervals returns the intersection of two intervals. More precisely, the operator returns the interval that defines the overlapping portion of both arguments.

I think we get the expected result by applying the definition: "the overlapping portion of both arguments." If we put the two intervals on a number line, we end up with something like the following:

```
Interval [1, 10  ]:       X   X   X   X   X   X   X   X   X   X   X
Interval [5, null):                       X   ?   ?   ?   ?   ?   ?
                      0---1---2---3---4---5---6---7---8---9---10--11--...
```

We _know_ that 5 is definitely in the overlap, and since the `null)` end boundary means "unknown end", it's possible that other numbers past 5 are in the overlap (or not). The way we represent the interval from _definitely_ 5 to _some unknown end_ is `Interval [5, null]`.

So while the spec doesn't explicitly tell you what to do with null boundaries here, this is the answer you get if you follow the existing semantics of the spec that define intervals in terms of overlaps and `null)` as an unknown endpoint.

**Comment by holly-smile** [comment]
That makes sense! I do want to express my concerns with how this goes back on precedent - it makes a lot of sense to me for behavior around Intervals to use the same greater-than and less-than comparison behavior as is used elsewhere, and I worry that for Intervals to do otherwise would be surprising in a bad way. That said, I'll happily taking a swing at implementing it now!
