### ISSUE TITLE
Dividing quantities with like units

### ISSUE THREAD

**Issue by cmoesel** [cqframework/clinical_quality_language#193]
In the CQL specification, it states:

> For division operations involving quantities, the resulting quantity will have the appropriate unit.
> For example:
> ```
> 12 'cm2' / 3 'cm'
> ```
> In this example, the result will have a unit of 'cm'.

What happens when the units are compatible and in the same dimension?  For example:
```
12 'cm' / 3 'cm'
```
The correct answer is `4`, but the spec indicates that a Quantity divided by a Quantity results in a Quantity.  So does this have to come back as a Quantity with a null unit, empty string unit, or something else?  Or can it be returned as a Integer/Decimal?

**Comment by brynrhodes** [comment]
Looking at the UCUM spec, I believe the way to represent this in UCUM is as a dimensionless quantity, which would have the default unit `1`.

**Comment by brynrhodes** [comment]
I think it would make sense to submit this as a comment to the CQL specification to clarify the semantics (it took a long time to parse that answer out of the UCUM spec).

**Comment by rdingwell** [comment]
I think the comment should also ask for clarification on what to do about a statement such as this.

(12 'cm' / 3 'cm') = 4 

Something similar to this is what I was using as a test case when adding ucum based operations and resulted in the parser throwing an exception because = operation was not allowed on (Quantity, Integer).

**Comment by brynrhodes** [comment]
This is a good point, we specifically disallowed implicit conversion from a integer/decimal to a quantity, because we couldn't justify picking a "default" unit. But after this discussion, I'm comfortable asserting that the default unit in UCUM is `1`, and so the comment should ask for an implicit conversion there as well.

**Comment by cmoesel** [comment]
Sounds like a good resolution.  What do you think, @rdingwell?

**Comment by rdingwell** [comment]
Just so I'm clear, the idea would be for division operations that create a null unit, that unit would be set to 1, which would be the default to represent a quantity without units?

**Comment by brynrhodes** [comment]
That's correct.

**Comment by rdingwell** [comment]
Ok, so that allows for implicit conversion to say an Integer or Decimal.  So when something like this happens 

(12 'cm' / 3 'cm') * 12 

The result will be?  Would this be the integer 36 or would it be the Quantity 36 '1'?  
This would probably result in more runtime errors if it is returned as a Quantity where incompatible types are supposed to throw exceptions when performing operations on them?  Or, are we saying that if the unit is 1, it really is just the base of the value of the quantity.  So something like this would not throw an exception.

5 'm' * (12 'cm' / 3 'cm') 

Would this be 20 'm' or runtime exception because the units are not related? 

I know I'm coner casing this with a lot of contrived examples but I just want to understand what the ramifications would be in a runtime environment.

**Comment by cmoesel** [comment]
I think that the unit `'1'` is kind of like `1` works in multiplication or division:
* if you multiply a number by 1, you get the number
  * if you multiply a unit by the unit `1`, you get the unit
* if you divide a number by 1, you get the number
  * if you divide a unit by a unit `1`, you get the unit
* if you divide 1 by a number, you get 1/n
  * if you divide a unit `1` by a number, you get... ?

OK.  So I don't know the answer to that last one.

**Comment by brynrhodes** [comment]
The implicit conversion would always be widening (conversion from Integer/Decimal to Quantity, never from Quantity to Integer/Decimal) because the narrowing conversion would lose information and so should never be implicit.

    (12 'cm' / 3 'cm') * 12

Would return `48 '1'`, and:

    5 'm' * (12 'cm' / 3 'cm')

Would return `20 'm'`.

As far as the division question, the resulting unit would be `'/1'`, according to my reading of the UCUM specification.

**Comment by rdingwell** [comment]
I think as long as the expected behavior is clear in the spec then that should work out ok.  I think it will really just boil down to some special case handling of quantities with the unit set to 1 in a runtime environment.  

Though this does seem to mean that for all expressions that contain a Quantity any Integer/Decimal contained within that expression would be implicitly converted to a Quantity.  So something like this which was not allowed before will now be allowed and result in a runtime, not a compile/design time error.

1 / 3 'm' 

So this becomes a trade off for what you would want people authoring content to be aware of and take care of as they are writing their CQL statements and what you would push out into the runtime.

**Comment by rdingwell** [comment]
I think setting the unit to '/1' is way more trouble than it is worth.

**Comment by brynrhodes** [comment]
I'm happy to leave that as an implementation detail.

**Comment by brynrhodes** [comment]
Submitted comment [1442](http://www.hl7.org/dstucomments/showdetail_comment.cfm?commentid=1442) and [1443](http://www.hl7.org/dstucomments/showdetail_comment.cfm?commentid=1443)

**Comment by duncand** [comment]
A few notes of my own:

1. In the general case, both Multiply and Divide might result in the neutral unit `1`.  After all, `4'm' / 4'm'` is the same value as `4'm' * 4'/m'`.

2. I would expect there is no such thing as a distinct `/1` unit, or at least while it is valid syntax it would always trivially normalize to `1`.

3. If you divide a unit 1 by a number N, you get the Decimal reciprocal of N paired with unit 1, for example `1'1' / 4` becomes `0.25'1'`.  It is very intuitive.

4. There is nothing logically wrong with `1 / 3 'm'` as an expression or a value, it should be allowed.
