### ISSUE TITLE
Issue with Same Or Before operator

### ISSUE THREAD

**Issue by JSRankins** [cqframework/clinical_quality_language#233]
The following expression passes CQL-to-ELM validation: 

```
["Encounter, Performed": "URI Visit"] URIencounter
    with ["Diagnosis": "Upper Respiratory Infection"] URI
        such that URI.prevalencePeriod starts during URIencounter.relevantPeriod
        or (URI.prevalencePeriod starts same or before URIencounter.relevantPeriod
        and URI.prevalencePeriod overlaps URIencounter.relevantPeriod) 
``` 

Note: This should fail per the signature for _same or before_ in CQL R1.2, since the right-hand side for _starts same or before_ is an interval and not datetime:

```
URI.prevalencePeriod starts same or before URIencounter.relevantPeriod
```

Same issue happens with _same or after_. Neither operator requires a datetime/time to be on the left- or right-hand side.

On the other hand, section 2.5.5.2 of CQL R1.2 seems to imply that _same as_ or _before_ can be used to compare two intervals, and that because of this, _same or before_ or _same or after_ could also be used to compare one interval with another. But if this is true, then the signatures for _same or before_ or _same or after_ do not appear to be completely documented in Appendix B. 

In addition to the above information, there is a noted documentation issue with the _same or before_ signature in Appendix B that was logged today: https://www.hl7.org/dstucomments/showdetail_comment.cfm?commentid=1426.

Thoughts?

**Comment by brynrhodes** [comment]
The comment on the STU is a different issue, but still an errata in the spec. The issue you're highlighting here is that the spec isn't clear that "same or before" and "same or after" are the same operators as "on or before" and "on or after" when an interval is involved in the left or right, or both, operands.

So that's another comment to clarify in section 9.9.17 and 9.9.18 that "same" is a synonym for "on". I'll add that as a comment.

**Comment by brynrhodes** [comment]
Logged this as comment [1433](http://www.hl7.org/dstucomments/showdetail_comment.cfm?commentid=1433)
