### ISSUE TITLE
QDM v4.3 XSD

### ISSUE THREAD

**Issue by hhe-athena** [cqframework/clinical_quality_language#265]
We are looking to compile CQL utilizing QDM 4.3 as the current version of Cypress only supports QDM 4.3. Since we are working to certify by mid-year 2018 and Cypress isn’t planning on updating to QDM v5.3 until July or later, we wanted to start working with a consistent version of QDM 4.3. Could the team review and provide the QDM v4.3 schema file?

It would be great if this was also provided in future version updates as well.

**Comment by brynrhodes** [comment]
Since the XSD for 4.3 was draft, we reviewed it for accuracy against the currently published QDM 4.3 and found the following issues:

1. Two discrepancies are found:
1.1. Medication, Discharge: MedicationDischarge.cumulativeMedicationDuration is in the xsd but not in QDM
1.1. Medication, Dispensed: MedicationDispensed.reason is in the xsd but not in QDM
1. It looks like each QDM attribute is specified with cardinality of 0..1. However, Encounter.admissionDatetime and Encounter.dischargeDatetime are the two only attributes (among all attributes for all QDM datatypes) that have cardinality of 1..1 in the xsd.
1. The xsd itself appears to have problem with “Code” type definition.

We'll address these in the XSD and then produce a model info.

**Comment by brynrhodes** [comment]
Included in release 1.2.18
