### ISSUE TITLE
Issue with Retreives

### ISSUE THREAD

**Issue by jackcmeyer** [cqframework/clinical_quality_language#378]
Given the following CQL:

```
define "SDE Payer":
   ["Patient Characteristic Payer": "Payer"abc]
```

The translator does not result in an error. 

However, 
```
define "SDE Payer":
   ["Patient Characteristic Payer": "Payer"123]
```

results in `no viable alternative at input '["Patient Characteristic Payer": "Payer"123]'`.

**Comment by brynrhodes** [comment]
@jackcmeyer , thank you for the report. The issue here is that because the terminology portion of a retrieve can be an arbitrary expression, the CQL expression `"Payer"abc` is being interpreted as a "no-op query" with `"Payer"` as the source and `abc` as the alias.

We have plans to address this, see #178 and #179, we can consider this as a vote for implementation of those features.
