### ISSUE TITLE
Implicit Use of FHIRHelpers Functions

### ISSUE THREAD

**Issue by bdrillard** [cqframework/clinical_quality_language#382]
I'm noticing there seems to be a change in how the CQL-to-ELM project handles use of FHIRHelpers functions between versions 1.2.x and 1.3.x for FHIR 3.0.0.

The FHIR enumerated fields have their own types, but underneath are often represented as simple Strings nested in a "value". In CQL-to-ELM for 1.2.x, a FHIRHelper function was inferred and would then wrap any property call to such a field. However, the CQL-to-ELM compiler for version 1.3.x no longer seems to apply this implicit FHIRHelper function call. Taking `fhir:AdministrativeGender` as an example:

CQL

```
library Query version '1'
using FHIR version '3.0.0'

include FHIRHelpers version '3.0.0' called FHIRHelpers

context Patient

define GetGender: Patient.gender = 'female'
```

CQL-to-ELM v1.2.16 yields

```
      <def resultTypeName="t:Boolean" name="GetGender" context="Patient" accessLevel="Public">
         <expression resultTypeName="t:Boolean" xsi:type="Equal">
            <operand name="ToString" libraryName="FHIRHelpers" xsi:type="FunctionRef">
               <operand resultTypeName="fhir:AdministrativeGender" path="gender" xsi:type="Property">
                  <source resultTypeName="fhir:Patient" name="Patient" xsi:type="ExpressionRef"/>
               </operand>
            </operand>
            <operand resultTypeName="t:String" valueType="t:String" value="female" xsi:type="Literal"/>
         </expression>
      </def>
```

but CQL-to-ELM v1.3.10 yields

```
      <def resultTypeName="t:Boolean" name="GetGender" context="Patient" accessLevel="Public">
         <expression resultTypeName="t:Boolean" xsi:type="Equal">
            <operand resultTypeName="fhir:AdministrativeGender" path="gender" xsi:type="Property">
               <source resultTypeName="fhir:Patient" name="Patient" xsi:type="ExpressionRef"/>
            </operand>
            <operand resultTypeName="t:String" valueType="t:String" value="female" xsi:type="Literal"/>
         </expression>
      </def>
```

where the difference is the lack of a wrapping function call to `FHIRHelpers.ToString`.

I wondered if the definition of `Equal` was meant to capture the type-unwrapping here, but the [definition](https://github.com/cqframework/clinical_quality_language/blob/v1.3.10/Src/cql-lm/schema/elm/expression.xsd#L1070) doesn't seem to say anything about that.

My questions here are

1. what change eliminated the implicit wrapping of certain FHIRHelpers functions over these special FHIR types?
2. what was the thinking behind the change?

I ask because the definition of functions like [`ToString`](https://github.com/cqframework/clinical_quality_language/blob/v1.3.10/Src/java/quick/src/main/resources/org/hl7/fhir/FHIRHelpers-3.2.0.cql#L219) when dispatched over an enumerated value type like AdministrativeGender "unwrapped" the value nesting in the FHIR structure. Without the implicit call as realized in the ELM, I'm not sure it's clear anymore how a runtime implementation will have to unwrap the FHIR structure.

**Also**: Given that `ReferralRequest.status` is also an example of an enumerated field like `Patient.AdministrativeGender`, I think this question is related to #371.

**Comment by bdrillard** [comment]
Given that `ReferralRequest.status` is also an example of an enumerated field like `Patient.AdministrativeGender`, I think this question is related to #371.

**Comment by brynrhodes** [comment]
Thank you for the report, I'm looking into this, it certainly seems like the wrong behavior.

**Comment by rdingwell** [comment]
@brynrhodes I'm curious as to which you consider to be the wrong behavior?  Looking at the generated ELM it seems very odd to me that the inclusion of a CQL library would effect the output the way it does in the first example and unless there is something explicitly in the spec that says that's possible that would be the output that is incorrect.

**Comment by bdrillard** [comment]
Some earlier context here -- it's been the case since #89 that the FHIRHelpers library is included by default any time FHIR is used for the data model.

I think the need here is that all of FHIR's enumerated types, as well as some of its special string types, like `UriType`, are actually structures having a `value` field holding a simple String. Since FHIRHelpers is pulled in by default, the compiler could infer the correct function usage (or at least it did previously).

Agreed there's some ambiguity here. At the moment, I don't think the CQL spec says anything about this special, type-based function inference in the context of FHIR models, so that may surprise an implementor to see it in the generated ELM.

I will say once that inferencing is understood, it does make the job of a CQL **author**, since the author doesn't have to explicitly call `ToString` over FHIR values that they see to functionally just be Strings (even though the FHIRModels think of them in implementation as enumerators).

I'd say the inferred function use is also easier on an **implementor** because if we're consuming data to their FHIRModels' specs, these enumerated values and other special types _will_ be wrapped in a "value" field. It's helpful for the ELM to indicate at least in some manner that the structure needs to be "unwrapped" to get at the FHIR data's String value when necessary.

**Comment by brynrhodes** [comment]
@bdrillard, that's a fantastic summary of the background, thank you for that. @rdingwell, it's not the inclusion of the FHIRHelpers library that causes the implicit conversions to occur, it's the fact that the conversions are defined in the FHIR model info. The [Implicit Conversions](https://cql.hl7.org/03-developersguide.html#implicit-conversions) topic in the specification allows for data models to introduce their own implicit conversions, but to do so, the conversion definitions need to reference a function, which has to be defined in a library. So in order to take advantage of the conversions defined in FHIR, you have to include the FHIRHelpers library. To make that easier, the translator includes FHIRHelpers as a packaged resource, but I stopped short of automatically adding the include.

**Comment by rdingwell** [comment]
@brynrhodes thanks for the clarification.  I understand the intention behind the idea of the implicit conversions but I think you probably recall that I'm not a huge fan of such magic at times.  I believe this sort of thing can become a bit problematic when doing conversions on coded values as well.  Coded values are bound to code systems and allowing matching on just the value of the code without any acknowledgement of the code system that it is expected to be from seems a bit wrong.  

I see that the spec supports implicit conversions but feel the way that that functionality is defined could be a bit clearer.   From what I've seen I believe that the modelInfo.xsd is part of the specification, or at least included in the spec.  I think it needs to be very clear that using that XSD is the way to declare models across all implementations of CQL.   I also think that the ConversionInfo element is a bit vague, or at least there isn't any documentation on it that I have found.    The part that really bothers me about it is the function called for the conversion.  Is this supposed to be called from a helper library, if so, where is that library defined in the model, if it's not why not, it really seems important.  

Overall, I just think there needs to be more documentation around defining data models and maybe that would provide enough guidance as to how this is all supposed to work within an implementation. However,  I think it would be more beneficial to provide a data modeling capability directly within the language itself.  This would provide a way for models, helper functions and conversion methods to all be defined in a single location that all implementations could make use of without the need of a separate modeling technology.   I think this would actually assist authors a bit better than the current approach as well because all of the documentation about the model would be defined in a single file in a format that they understand as opposed to some xml file squirreled away somewhere.  

Just some thoughts.

**Comment by brynrhodes** [comment]
@rdingwell , this is a great suggestion and you're highlighting the fact that there's a disconnect between the model definition and the library definition. This was an early design decision in CQL based on the fact that we didn't want the scope of the language to include model definition. If we had model definition constructs in CQL, then we could include those in the library and "models" would just be part of libraries. Then the conversion info wouldn't have to reference a library name magically.

However, that's a pretty significant scope increase for CQL, have you considered submitting that as an STU comment? This would be a great thing to get in front of the community and see whether there's support for the idea.

**Comment by bdrillard** [comment]
Is there any word on confirming this issue? We'd like to upgrade to the latest version of the project, but this is a blocker for us. If the issue is confirmed, we'd wonder if either there's a fix just hiding in configuration somewhere, if there's a workaround, or if a fix would get slotted to a later release.

**Comment by bdrillard** [comment]
Thanks @brynrhodes, that would be ideal!

**Comment by rdingwell** [comment]
@brynrhodes finally found some time to get back to this, STU comment submitted.

**Comment by brynrhodes** [comment]
@rdingwell, I don't see a comment for this on the STU page: http://www.hl7.org/dstucomments/showdetail.cfm?dstuid=233

I want to make sure it's captured, where did you submit the STU comment?

**Comment by bdrillard** [comment]
I see the work done to resolve the initial reproducing test case:

```
library Query version '1'
using FHIR version '3.0.0'

include FHIRHelpers version '3.0.0' called FHIRHelpers

context Patient

define GetGender: Patient.gender = 'female'
```

which appears to have been to more parameterize the possible function arguments for equal/equivalent. Thanks for this.

It seems like this issue may apply to numerous operators. `SameAs` was an operator that previously could infer a `FHIR.dateTime` would need conversion to an appropriate System type, but this operator still fails after the changes to `equal`/`equivalent`.

**Comment by bdrillard** [comment]
I see the work done to resolve the initial reproducing test case:

```
library Query version '1'
using FHIR version '3.0.0'

include FHIRHelpers version '3.0.0' called FHIRHelpers

context Patient

define GetGender: Patient.gender = 'female'
```

which appears to have been to more parameterize the possible function arguments for equal/equivalent. Thanks for this.

It seems like this issue may still apply to a few [clinical operators](https://github.com/cqframework/clinical_quality_language/blob/6ff4a1ba4683aa6dc71cee0228e836afc6777035/Src/java/cql-to-elm/src/main/java/org/cqframework/cql/cql2elm/SystemFunctionResolver.java#L65), e.g. `AgeInYearsAt`. Consider

```
library Query version '1'
using FHIR version '3.0.0'

include FHIRHelpers version '3.0.0' called FHIRHelpers

context Patient

define TestSameAs: AgeInYearsAt(Patient.deceased)
```

which yields

```
CompilerException clojure.lang.ExceptionInfo: Errors encountered while parsing the query:
startLine: 8
startChar: 20
endLine: 8
endChar: 49
message: Expected an expression of type 'choice<FHIR.boolean,FHIR.dateTime>', but found an expression of type 'System.Date'.
errorType: semantic
errorSeverity: error
```

**Comment by brynrhodes** [comment]
@bdrillard, I think this is actually a different issue. The problem here is that the AgeInYearsAt function has two overloads (Date) and (DateTime), and because the actual ELM being called is CalculateAgeInYearsAt, the translator tries to use the type of the AgeInYearsAt argument to determine whether to call the "CalculateAgeInYearsAt(Date)" or "CalculateAgeInYearsAt(DateTime)". So to do that, it tries to force convert the Patient.birthDate to the type of the argument to the overload. So what's happening is the translator is trying to convert "Patient.birthDate" to a type of "Choice<FHIR.boolean, FHIR.dateTime>", and since there is no conversion path there, it fails (there is a path, but it requires two hops, and CQL does not support transitive implicit conversion). The reason it worked in the previous translator was that there was only a CalculateAgeInYearsAt(DateTime, DateTime) and so both arguments could be converted in one hop to DateTime. So to get this to work with the way this is defined, you have to say:
    
    AgeInYearsAt(FHIRHelpers.ToDateTime(Patient.deceased as FHIR.dateTime))

Which is not pretty, so I'm mulling this. Do you have any other examples that behave unexpectedly (and that don't involve the Age calculation functions)?

**Comment by brynrhodes** [comment]
@bdrillard, just pushed a commit that adds the expected behavior for `AgeInYearsAt(Patient.deceased)`. It will now implicitly convert the Patient.deceased to a DateTime and then use the DateTime overload of `CalculateAgeInYearsAt`.

**Comment by bdrillard** [comment]
I tested against a snapshot build, I can confirm both the issues discussed in this thread (application of implicit conversions, `AgeInYearsAt` FHIR dispatch) are fixed.

Thanks for the attention to them!

**Comment by brynrhodes** [comment]
Adressed in [1.3.14](https://github.com/cqframework/clinical_quality_language/releases/tag/v1.3.14)
