### ISSUE TITLE
CQL Translator produces Double List Promotion at Retrieve Codes

### ISSUE THREAD

**Issue by alexanderkiel** [cqframework/clinical_quality_language#408]
After updating from 1.3.10 to 1.3.14, the following CQL example translates to different ELM:
```
library Test
using FHIR version '4.0.0'
codesystem test: 'test'
code T0: '0' from test

define Observations: [Observation: T0]
```
The relevant part is the Retrieve Expression. Here you have the double list promotion:
```json
{
  "dataType" : "{http://hl7.org/fhir}Observation",
  "codeProperty" : "code",
  "type" : "Retrieve",
  "codes" : {
    "type" : "ToList",
    "operand" : {
      "type" : "ToList",
      "operand" : {
        "name" : "T0",
        "type" : "CodeRef"
      }
    }
  }
}
```
With version 1.3.10 I get:
```json
{
  "dataType" : "{http://hl7.org/fhir}Observation",
  "codeProperty" : "code",
  "type" : "Retrieve",
  "codes" : {
    "type" : "ToList",
    "operand" : {
      "name" : "T0",
      "type" : "CodeRef"
    }
  }
}
```
With disabled list promotion, I get no lists with both versions.

**Comment by brynrhodes** [comment]
Hi @alexanderkiel , thank you for the report. I have confirmed this behavior, it is a byproduct of list promotion, as well as some fixes to type resolution that were included in the 1.3.14 release.

In detail, what's happening is that within the retrieve, when the terminology target is a direct reference code, the translator will attempt to resolve equality in to validate the terminology target. The type resolution in 1.3.14 is tighter, so that resolution results in a failure if list-promotion is disabled (which shows up as a warning when resolving terminology targets). But with list-promotion enabled, the translator will opt to promote both sides to a list and allow the comparison (effectively pushing the equality determination to a run-time operation). And finally, because it's a direct-reference code, the translator assumes it needs to automatically promote the code to a list because the retrieve is expecting a list of codes (the failure here is that it is not checking whether the equality resolution actually resulted in a list promotion).


So the internal part about not resolving code equality correctly is actually an issue that is scheduled to be addressed in the first 1.4 release.

The other issue (not checking whether equality resolution resulted in list promotion, producing double-list promotion) I will address in this release.

**Comment by brynrhodes** [comment]
Due to timing constraints, moving this to the first 1.4 release. Let me know if this is critical to have resolved in 1.3, since the workaround is to disable list promotion.

**Comment by alexanderkiel** [comment]
I need FHIR R4 in about one week. I also use list promotion at least for the code attribute in retrieve. If I would disable list promotion, I would have to rebuild it myself. If you only need to release the fix you have already, I would appreciate it a lot. Thanks.

**Comment by brynrhodes** [comment]
Addressed in [v1.3.15](https://github.com/cqframework/clinical_quality_language/releases/tag/v1.3.15)

**Comment by brynrhodes** [comment]
https://github.com/cqframework/clinical_quality_language/releases/tag/v1.3.15

**Comment by alexanderkiel** [comment]
Thank you for this release. Unfortunately there is still misplaced list promotion in the following query:
```
library Retrieve version '1.0'
using FHIR version '3.0.0'

context Patient
context Population

define Patients:
  from [Patient] P
    with [Condition] C
      such that P = C.subject
```
I did not see this before but it was already in v1.3.14. In the `Equal` expression of `such that` both operands are promoted to lists.

**Comment by alexanderkiel** [comment]
The second thing, I noticed, is that the expression in `TestEqualNull` in group `Equal` of [CqlIntervalOperatorsTest.xml][1] now also produces a rather strange ELM tree. The expression is:

```
Interval[1, 10] = Interval(null, null)
``` 
The ELM tree is somehow to big to paste here. But you will see `Property` expressions for the bounds in the `Interval(null, null)`.

Before v1.3.10 already created these `Property` expressions in the following tests: `TestEndsNull`, `TestInNull` and `TestProperlyIncludedInNull`.


[1]: <https://github.com/HL7/cql/blob/master/tests/cql/CqlIntervalOperatorsTest.xml>

**Comment by alexanderkiel** [comment]
The third thing I noticed, is that the tests `SimpleEqNullNull`, `SimpleNotEqNullNull` and `EquivNullNull` from [CqlComparisonOperatorsTest.xml][1] no longer translate. The errors are like this: 
```
Call to operator Equal(System.Any,System.Any) is ambiguous
```
As the equality operators should work with any type, I think the tests are right here and the type inference should be able to handle such situations.

[1]: <https://github.com/HL7/cql/blob/master/tests/cql/CqlComparisonOperatorsTest.xml>

**Comment by brynrhodes** [comment]
Hi @alexanderkiel , the ability to use a code as a terminology target is already supported, that's a special-case "list promotion" that occurs whether or not list promotion is enabled. With list promotion disabled, the translator returns a more appropriate error in that case:

    Error:[10:17, 10:29] Could not resolve call to operator Equal with signature (FHIR.Patient,FHIR.Reference).

The fact that this translated before is the issue that we're addressing with this release. There is definitely still a known issue here, but I'm curious what the expected behavior here is? I can see how conceptually a Patient could compare equal to a reference to a Patient, it makes sense what you're trying to do, but it's definitely not expected behavior and would require data access layers to resolve the equality of an instance and a reference. Does your data access layer resolve this automatically?

**Comment by brynrhodes** [comment]
As a side note, it's really interesting that you're using Population context. Just a heads up that we are proposing this context be renamed in CQL 1.4 (same semantics, just a new name). Would love to chat some time about what you are doing with population context CQL.

**Comment by alexanderkiel** [comment]
> Hi @alexanderkiel , the ability to use a code as a terminology target is already supported, that's a special-case "list promotion" that occurs whether or not list promotion is enabled. With list promotion disabled, the translator returns a more appropriate error in that case:
> 
> ```
> Error:[10:17, 10:29] Could not resolve call to operator Equal with signature (FHIR.Patient,FHIR.Reference).
> ```
> The fact that this translated before is the issue that we're addressing with this release. There is definitely still a known issue here, but I'm curious what the expected behavior here is? I can see how conceptually a Patient could compare equal to a reference to a Patient, it makes sense what you're trying to do, but it's definitely not expected behavior and would require data access layers to resolve the equality of an instance and a reference. Does your data access layer resolve this automatically?

Good point. I did not think about that `Equal` isn't defined for `FHIR.Patient` and `FHIR.Reference` because my data access layer has the FHIR entities at hand and allows `Equal` on them. I looked up some examples in authors guide and they do `Equal` on `identifier`. This query works in v1.3.15:

```
library Retrieve version '1.0'
using FHIR version '3.0.0'
include FHIRHelpers version '3.0.0'

context Patient
context Population

define Patients:
  from [Patient] P
    with [Condition] C
      such that P.id = C.subject.id
```

**Comment by alexanderkiel** [comment]
> As a side note, it's really interesting that you're using Population context. Just a heads up that we are proposing this context be renamed in CQL 1.4 (same semantics, just a new name). Would love to chat some time about what you are doing with population context CQL.

I've already seen the change in 1.4. I'll write to you in the FHIR chat.

**Comment by alexanderkiel** [comment]
Thanks. I rewrote my queries and was able to update to v1.3.15. Only my comments about the equal tests and the `TestEqualNull` are still relevant. Should I open separate issues on that?
