### ISSUE TITLE
Issues with current QDM 5.5 Model Info

### ISSUE THREAD

**Issue by JSRankins** [cqframework/clinical_quality_language#423]
A review of the QDM 5.5 Model Info file against the recently published QDM 5.5 reveals a number of issues. Please see below.

- In QDM 5.5, relevant period was removed for Adverse Event, but it is still in the model info file.

- The model info file establishes a base Entity type that it uses as the foundation for all entities - patient, care partner, practitioner and organization. This base Entity type contains two attributes - id and identifier. 

    <ns4:typeInfo xsi:type="ns4:ClassInfo" name="QDM.Entity" baseType="System.Any" retrievable="false">
        <ns4:element name="id" type="System.String"/>
        <ns4:element name="identifier" type="QDM.Identifier"/>
    </ns4:typeInfo>

QDM does not mention the id attribute for the entity types - just identifier. Other than the types used for these attributes in the model info file (String for id and Identifier for identifier), it is not clear what the semantic difference is between id and identifier. Is having the extra id attribute available for all entity attributes by design, or is this a bug? If it is by design, can clarification be provided on how these are supposed to be used, since QDM does not mention Entity.id?

- In the QDM 5.4 Model Info File, id in the QDMBaseType was typed to QDM.Id. QDM.Id allowed for namingSystem and value attributes. The QDM 5.5 Model Info File updated the QDM.Id type to QDM.Identifier. However, instead of pointing to this modified name, the QDM 5.5 Model Info File now types id to a String, which does not allow for the level of specificity that QDM.Id used to. Is there a reason for the change?

- The patientId attribute in the QDMBaseType is not listed in QDM. Based on e-mails a couple years ago with ESAC and MITRE, the patientId attribute was being used for Health Record Field. The Health Record Field has been removed with QDM 5.5. Is there a reason for keeping this attribute? If it remains, is there a reason its type was changed from QDM.Id to String?

- Entity attributes are using a choice type that includes the Patient datatype. We believe this should be the PatientEntity datatype instead. As is, any entity attribute can use birthDatetime. For example, the following runs successfully against the translator:

`define "X":
	["Adverse Event"] AE
		where AE.recorder is Patient
			and AE.recorder.birthDatetime > @2012-01-02`

- For "Assessment, Performed": In the QDM 5.4 Model Info File, relatedTo was typed to List<QDM.Id>. QDM.Id allowed for namingSystem and value. The QDM 5.5 Model Info File updated the QDM.Id type to QDM.Identifier. However, instead of pointing to this modified name, the QDM 5.5 Model Info File now types relatedTo to a List<String>, which does not allow for the level of specificity that QDM.Id used to. Is there a reason for the change?

- The Model Info File is using "recorder" instead of "requester" for "Assessment, Order". Per QDM, it should be "requester".

- For "Care Goal" - In the QDM 5.4 Model Info File, relatedTo was typed to List<QDM.Id>. QDM.Id allowed for namingSystem and value. The QDM 5.5 Model Info File updated the QDM.Id type to QDM.Identifier. However, instead of pointing to this modified name, the QDM 5.5 Model Info File now types relatedTo to a List<String>, which does not allow for the level of specificity that QDM.Id used to. Is there a reason for the change?

- Sections 3.6, 4.1.5 (Care Goal Datatype table) and 4.2 (Table 25) in QDM list the attribute "status date" for "Care Goal". However, section B.1 has the attribute listed as "status datetime". Which is correct? If it should be "status date", then the Model Info File needs to be updated.

- For "Care Goal" - Sections 2.4.1, 4.1.5 (Care Goal Datatype table) and 4.2 (Table 25) in QDM list the attribute "performer" for "Care Goal". However, there is a parentheical comment in  Table 25 for Care Goal - "ExpressedBy". The Model Info File has the attribute as expressedBy. Which is correct? If it should be "performer", then the Model Info File needs to be updated.

- For "Communication Performed" - In the QDM 5.4 Model Info File, relatedTo was typed to List<QDM.Id>. QDM.Id allowed for namingSystem and value. The QDM 5.5 Model Info File updated the QDM.Id type to QDM.Identifier. However, instead of pointing to this modified name, the QDM 5.5 Model Info File now types relatedTo to a List<String>, which does not allow for the level of specificity that QDM.Id used to. Is there a reason for the change?

- QDM 5.5 added a participant attribute for "Encounter, Performed". This attribute is missing in the Model Info File.

- QDM has "relationships" as an attribute for "Family History". The Model Info File has this attribute as "relationship" (i.e., singular, not plural). Which is correct?

- The Model Info File has "relevantPeriod" and "relevantDatetime" for "Immunization, Administered". QDM only lists "relevantDatetime". Which is correct?

- The Model Info File has "prescriberId" for "Medication, Order". The "prescriberId" attribute was removed with QDM 5.5 with the addition of "prescriber".

- The Model Info File has "relevantDatetime" for "Medication, Order". The "relevantPeriod" attribute does not exist in QDM for this datatype in the "Medication, Order" datatype table (pg. 42), but section 3.1 (pg. 18), table 2 (pg. 21) and the attribute table (pg. 70) list this attribute for this datatype . Which is correct?

- The relationship attribute needs to be added for Related Person in QDM 5.5 Model Info File.

- QDM 5.5 states that code is allowed for all datatypes except 'Related Person'. The QDM 5.5 Model Info File allows for code to provided for Related Person.

- The Model Info File has an "identifier" attribute for the new "Related Person" datatype, as well as and id attribute. QDM lists two attributes for this datatype in the "Related Person" datatype table (pg. 50): id and relationship. However, since "Related Person" is supposed to be the equivalent of the carePartner entity, which has an identifier attribute, we are wondering what is correct. If "Related Person" should have both the id and identifier attributes, it is not clear what the difference is between these two attributes. Please clarify.

- QDM 5.5 added a relevantPeriod attribute for "Substance, Order". This attribute is missing in the Model Info File.

- Entity.id is not mentioned in QDM. Identifier is. Is there a reason for having the Entity.id attribute in addition to the identifier attribute?

**Comment by FEisenberg** [comment]
From a QDM perspective, I'd like to hear feedback from Bryn. We can discuss on the Friday CQL-based HQMF call but that is 3 days away. 

- Entity.id - correct that QDM does not specify it - if needed, it is an easy "fix" in errata documentation but need to know if it needs QDM documentation or just assumptions for the model info.

- Immunization, Administered only has Relevant dateTime (not Relevant Period) as actual times -this is intentional to stay aligned with FHIR Immunization

- QDM Family History assumed that only 1 relationship is relevant for each instance - based on discussions

- Medication, Order includes author dateTime for the time the order is written, and Relevant Period to address the time period when the order is to FHIR MedicationRequest validity period - i.e., the time period the order is authorized to be dispensed. Section 3.1 (page 18) includes Relevant Period as applied to Medication, Order as does the attribute table (page 80) - but the Medication, Order section specifically defines it as noted. Thus, Relevant dateTime does not exist for Medication, Order - only Relevant Period and that refers to the validity period as expressed in FHIR Resources. Hopefully that helps.  In the QDM document, the specific QDM datatype defines how each Relevant Period is to be specified for that QDM datatype.

- For QDM 5.5 Related Person the lack of "identifier" was not intentional and it is more of an errata if it is needed. It should be modeled the same as Care Partner.  We need to discuss how to do that from the QDM publication perspective.

I think that addresses the specific QDM questions but I look forward to further discussion.

**Comment by brynrhodes** [comment]
Thank you for the detailed review, very much appreciated. I have addressed the issues as follows:

* Removed relevantPeriod from AdverseEvent

* The id attribute of the Entity base type is meant to serve the same purpose as the id attribute in the QDM base type, it provides an instance id, whereas the identifier attribute is a logical (or business) identifier. Instance ids are used by the underlying systems to represent the unique, system-specific identifier for an item, and as such don't need the naming system. Whereas business identifiers can potentially contain external identifiers and so need a naming system to establish the authority for the identifier. For cases where entities are used to capture information that is completely dependent, there will not be an instance identifier, since the entity only has meaning in the context of the containing instance. But for cases where entities are capturing a reference to another underlying instance (CarePartner or Practitioner, for example), the id is used to represent the system id for the item.

* The change from QDM.Id to QDM.Identifier solidifies the design pattern of using Id for instance identity, and Identifier for business identifiers (that can be both internal and external).

* The patientId attribute in the QDMBaseType establishes the patient context for all data types. It is necessary in the implementation to allow the underlying data to represent the relationships between the QDM data elements and the patient instance. Especially with the addition of related-context retrieve, being able to represent the patient for which this data is applicable is critical.

* Fixed all Entity choices that referenced Patient to reference PatientEntity

* The change to "Assessment, Performed".relatedTo from List<QDM.Id> to List<String> is recognizing that the relationship is represented using instance ids, not business identifiers.

* Changed "Assessment, "Order".recorder to requester

* The change to "Care Goal".relatedTo from List<QDM.Id> to List<String> is recognizing that the relationship is represented using instance ids, not business identifiers.

* "Care Goal".statusDatetime, I would suggest statusDatetime is the more useful, since it can capture both Datetime and Date, but defer to @FEisenberg for the correct attribute name.

* "Care Goal".expressedBy, I defer to @FEisenberg for the correct attribute name.

* The change to "Communication, Performed".relatedTo from List<QDM.Id> to List<String> is recognizing that the relationship is represented using instance ids, not business identifiers.

* Added participant entity attribute to "Encounter, Performed"

* "Family History", I used the name from the Attributes table (singular), and recommend singular because the cardinality is 0..1, but defer to @FEisenberg for the correct attribute name.

* Corrected Immunization, Administered to only list relevantDatetime

* Removed prescriberId from Medication, Order

* Removed relevantDatetime from Medication, Order

* RelatedPerson already has a code attribute, by virtue of being a QDM data type, and so we should use that for the "relationship", consistent with the use of code to establish types. @FEisenberg , this would need an errata in QDM.

* The id attribute in CarePartner and RelatedPerson establishes instance identity, whereas the identifier attribute is a logical, or business identifier.

* Added relevantPeriod to Substance, Order

* Entity.id serves the same purpose as QDMBaseType.id, providing an internal instance identity. In cases where the entity "maps" to a data type, the instance identities would be the same.

**Comment by brynrhodes** [comment]
Included in 1.4.2-SNAPSHOT
