### ISSUE TITLE
CQL-to-ELM Translator - Could not resolve call to operator ToQuantity with signature (System.Ratio)

### ISSUE THREAD

**Issue by sanumula** [cqframework/clinical_quality_language#464]
The cql-to-elm translator fails for the ToQuantity overload for Ratio type as shown below.

**CQL:**
```
using FHIR version '3.0.0'

context Patient

define RatioOverload: ToQuantity(0.1 'mg':0.2 'mg')
```

**Error:**
```
Translation failed due to errors:
Error:[5:23, 5:51] Could not resolve call to operator ToQuantity with signature (System.Ratio).
```

CQL Spec: https://cql.hl7.org/09-b-cqlreference.html#toquantity

CQFramework version: 1.3.15

**Comment by brynrhodes** [comment]
This overload was introduced in the STU4 release of CQL:
https://cql.hl7.org/09-b-cqlreference.html#toquantity

It was not present in the STU3 release:
https://cql.hl7.org/STU3/09-b-cqlreference.html#toquantity

So this behavior is expected in the 1.3 translator.

The 1.4 behavior is simply to perform the division specified by the ratio, so that is a workaround in 1.3.
