### ISSUE TITLE
Deduplicate JAXB dependencies

### ISSUE THREAD

**Issue by brynrhodes** [cqframework/clinical_quality_language#529]
We should attempt to deduplicate JAXB dependencies.

**Comment by JPercival** [comment]
The cql-translator relies on the eclipselink moxy implementation of JaxB in order to be able to do JSON serialization of ELM. However, within the project there were references to the reference implementation of JaxB. This was causing build warnings due to overlapping packages.

In the time since the translator was started the landscape around Java EE has changed. Oracle has donated the reference implementation to Eclipse and it's been renamed to Jakarta.

In the translator we should standardize on one implementation (which is moxy in order to support the JSON serialization) and update the dependencies, versions, etc. to reflect the Java EE changes.

**Comment by brynrhodes** [comment]
Addressed in 1.4.9 release
