### ISSUE TITLE
Annotations in JSON

### ISSUE THREAD

**Issue by brynrhodes** [cqframework/clinical_quality_language#61]
Annotations in XML work as expected because the content of the annotation is an html fragment. However, when the ELM is output as JSON, the rendering is very difficult to reconstruct. There needs to be a better way to communicate the content of the annotation when the output is formatted using JSON.

**Comment by pkmitre** [comment]
The current XML annotation is difficult to represent in JSON because the XML uses mixed content, ie

    <annotation xsi:type="a:Annotation">
      <a:s r="27">
        define PatientAge:
        <a:s r="26">
          AgeInYearsAt(
          <a:s r="25">
            start of
            <a:s r="24">MeasurementPeriod</a:s>
          </a:s>
          )
        </a:s>
      </a:s>
    </annotation>

In the JSON, all of the text strings within a tag, regardless of ordering relationship to other neighbor tags, are simply represented as an array of strings, ie

                    "value": [
                      "AgeInYearsAt",
                      "(",
                      ")"
                    ]

The relationship of the strings to the other tags is not preserved. Would it work to simply avoid the use of mixed content? For example, something like

    <annotation xsi:type="a:Annotation">
      <a:s r="27">
        <a:s>define PatientAge:</a:s>
        <a:s r="26">
          <a:s>AgeInYearsAt(</a:s>
          <a:s r="25">
            <a:s>start of</a:s>
            <a:s r="24">MeasurementPeriod</a:s>
          </a:s>
          <a:s>)</a:s>
        </a:s>
      </a:s>
    </annotation>

This could be represented in unambiguous JSON.

**Comment by brynrhodes** [comment]
This issue was corrected by pull request #94 and the fix will be included in the next release.
