### ISSUE TITLE
Minimum date test case

### ISSUE THREAD

**Issue by brynrhodes** [cqframework/clinical_quality_language#65]
[Minimum Date Test Case CQLIT-17](https://oncprojectracking.healthit.gov/support/browse/CQLIT-17)

i note the spec says (p154):

Description:
The DateTime type represents date and time values with potential uncertainty within CQL.
CQL supports date and time values in the range @0001-01-01T00:00:00.0 to @9999-12-
31T23:59:59.999 with a 1 millisecond step size.

however there there is a test case defined which suggest this should throw:

define Predecessor_min_date: predecessor of DateTime(1900,01,01,0,0,0,0)

https://github.com/cqframework/clinical_quality_language/blob/master/Src/coffeescript/cql-execution/test/elm/arithmetic/test.coffee#L344

**Comment by cmoesel** [comment]
I can't say for sure, but I suspect that this is due to the fact that the execution framework was written while the spec was still evolving.  Perhaps when this test was written (Dec 2014), the minimum date _was_ 1900.  At any rate, hopefully it's a single line fix here:

https://github.com/cqframework/clinical_quality_language/blob/dd0c71ce148652242ec0f6bc3493db1a07a30527/Src/coffeescript/cql-execution/src/util/math.coffee#L10

and here:

https://github.com/cqframework/clinical_quality_language/blob/dd0c71ce148652242ec0f6bc3493db1a07a30527/Src/coffeescript/cql-execution/src/datatypes/datetime.coffee#L269

(plus whatever tests need to be modified to compensate).

**Comment by cmoesel** [comment]
Fixed in #121
