### ISSUE TITLE
Compiler errors for age functions

### ISSUE THREAD

**Issue by brynrhodes** [cqframework/clinical_quality_language#66]
[CQLIT-16](https://oncprojectracking.healthit.gov/support/browse/CQLIT-16)

compiling this:

265 // @Test: CalculateAge
266 define Years: AgeInYears()
267 define Months: AgeInMonths()
268 define Days: AgeInDays()
269 define Hours: AgeInHours()
270 define Minutes: AgeInMinutes()
271 define Seconds: AgeInSeconds()
272
273 define Age:
274 AgeInYearsAt(start of age_MeasurementPeriod)
275
276 // @Test: CalculateAgeAt
277 define AgeAt2012: AgeInYearsAt(DateTime(2012))
278 define AgeAt19810216: AgeInYearsAt(DateTime(1981, 2, 16))
279 define AgeAt1975: AgeInYearsAt(DateTime(1975))

i get:

[266:15, 266:26] Internal translator error.
[267:16, 267:28] Internal translator error.
[268:14, 268:24] Internal translator error.
[269:15, 269:26] Internal translator error.
[270:17, 270:30] Internal translator error.
[271:17, 271:30] Internal translator error.
[274:3, 274:46] Internal translator error.
[277:19, 277:46] Internal translator error.
[278:23, 278:57] Internal translator error.
[279:19, 279:46] Internal translator error.

is this known?

and this on too...

define List_MixedList: List<Any>
{ 1, 'two', Three }

**Comment by cmoesel** [comment]
I don't know if it is related, but I think the coffee-script execution code has come out of synch with the CQL/ELM translator code.  If I run the task to generate the execution test data json files, I get many more errors than there used to be.

I think there may be merit to keeping the execution code in a separate repo so it can depend on locked down versions of CQL/ELM rather than being in the same repo where it must always compile against the HEAD of the branch...  It's probably something we should discuss at some point.

**Comment by brynrhodes** [comment]
Closing this issue as it's addressed by the move of the execution engine to a separate repo.
