### ISSUE TITLE
Add line information to the annotation output of the translator.

### ISSUE THREAD

**Issue by brynrhodes** [cqframework/clinical_quality_language#70]
Per the following issue logged at the CQL Issues Tracker, we will add line information to the annotation output of the translator:

https://oncprojectracking.healthit.gov/support/browse/CQLIT-8

The approach involves adding an "li" element to the annotation that contains a string with the line information "<line>:<character>".

Because it's part of the annotations, it will not be part of the core ELM output.

We could also consider adding the li element to the base expression, and controlling output with a "debug" flag.

**Comment by brynrhodes** [comment]
Deferring the implementation of this to CQL 1.2...

**Comment by cmoesel** [comment]
Couldn't this also be a potential _replacement_ for spans?  In other words, instead of including spans in the annotation text, the text remains as raw CQL and then separate elements(xml)/object(json) relate expressions/sub-expressions to line#/char# in the text.

In this way, it would even be possible to simply include the full CQL text as a single source annotation at the top of the document, and then all expression/sub-expression annotations just refer to ranges in the master CQL text.  I think this may be how I originally implemented it way back in v0.0.0.0.0.1 (fictional version number indicating how immature the translator was when I did it).

**Comment by brynrhodes** [comment]
Yes, that would be a potential solution for sure. The reason we opted for spans with pointers to the nodes, rather than line numbers in the nodes was that line numbers and positions can often get mangled as the text goes through different encodings, so it was felt that it would be more error-proof to use an HTML-style span to link the text back to the nodes.

That being said, I'd be happy to offer this solution as an interim for the link-spanning (which turns out to be quite complicated, and I wonder that it may even involve an after-the-fact visit to produce it, rather than being able to build it up during the translation as we try to do now).

**Comment by edeyoung** [comment]
Could you post an example of what this might look like?

**Comment by brynrhodes** [comment]
See the _Debug example [here](https://github.com/cqframework/clinical_quality_language/blob/v12/Examples/ChlamydiaScreening_CDS_Debug.json). The "locator" element provides line information, based on the original source file (not the annotation source).

**Comment by brynrhodes** [comment]
The 1.2 translator now includes an option for outputting original source locator information.
