### ISSUE TITLE
Update to Java 11 as minimum required version

### ISSUE THREAD

**Issue by JPercival** [cqframework/clinical_quality_language#741]
Version 6.0 of HAPI (in prerelease as of the time of this writing) requires Java 11. The cql-translator uses some HAPI APIs to generate data-requirements for CQL files. In order to update to the latest HAPI releases, the cql-translator will need to be updated to 11 as a minimum as well.

https://hapifhir.io/hapi-fhir/docs/introduction/changelog.html#hapi-fhir-600-prerelease

To do the upgrade we need to change gradle build to the correct Java version, ensure the CI pipeline is updated to use the correct version, and gather feedback from the community on the timing of the change from 8 to 11.

**Comment by JPercival** [comment]
See also #582 and #512

**Comment by vitorpamplona** [comment]
I did a quick migration to Java11 and everything seems to work fine. 

We should add: `targetCompatibility = JavaVersion.VERSION_11` to `build.gradle` to imply minimum version of Java 11. 

Since Java11 removes JAXB, the upgrade requires migrating `JAXB commons` from `0.12.0` to `1.11.1` and the JAXB runtime dependency below to the `xds-to-modelInfo` model: 
- ```    implementation group: 'org.jvnet.jaxb2_commons', name: 'jaxb2-basics-runtime', version: '1.11.1'```

Related to #582 and #512, I also tested migrating to Gradle from `5.6.2` to `7.4.2`, which requires us to: 
1. Rework the [deprecated maven publishing configuration](https://docs.gradle.org/6.9.2/userguide/upgrading_version_5.html#legacy_publication_system_is_deprecated_and_replaced_with_the_publish_plugins) to use the [new plugin](https://docs.gradle.org/current/userguide/publishing_maven.html)
2. Update a these scopes: 
  - `compile` to `implementation`
  - `testCompile` to `testImplementation`
  -  `runtime` to `runtimeOnly`
