### ISSUE TITLE
CQL to ELM conversion main method not found

### ISSUE THREAD

**Issue by nehaghub** [cqframework/clinical_quality_language#775]
Hi,

I have configured project and performed all required steps before CQL to ELM conversion.
When i am executing below command
**C:\Documents\HDE\clinical_quality_language-master\clinical_quality_language-master\Src\java> ./cql-to-elm/build/install/cql-to-elm/bin/cql-to-elm --format=JSON --input ../../../../cql-execution-master/examples/node/age.cql --output ../../../../cql-execution-master/customCQL**

I am getting this error

**Error: Main method not found in class org.cqframework.cql.cql2elm.CqlTranslator, please define the main method
as:
public static void main(String[] args)
or a JavaFX application class must extend javafx.application.Application**

Please let me know how to resolve this error .

Thank you.

**Comment by brynrhodes** [comment]
Hi @nehaghub we moved the translator main class to the cql-to-elm-cli package, and it looks like we didn't reflect that change in the instructions here. I'll mark this as a bug and get that fixed. In the meantime, if you switch to the v15 branch, you should still be able to run following these instructions.

Apologies for the mixup, we're refactoring the translator so that it can be run on Android devices and we're having to move some things around.

**Comment by nehaghub** [comment]
Thank you Brynrhodes for this useful information.

**Comment by nehaghub** [comment]
Hi,
I run this using branch v15. It is converting cql to elm json format. But, with this json format we can't ingest in FHIR store.
Do you have any idea how can we do mapping from elm json to fhir json.

Thanks!

**Comment by brynrhodes** [comment]
Apologies for the delay here, ELM json is represented in FHIR using the FHIR Library resource as the content element. For an example, see the CQF libraries here: http://fhir.org/guides/cqf/common/Library-FHIRCommon.html
The FHIR IG publisher will package CQL libraries this way using the binary-adjunct-files parameter, or you can use the CQF Tooling, as described in this walkthrough: https://github.com/cqframework/content-ig-walkthrough#content-ig-walkthrough
