### ISSUE TITLE
Outputting to System.Error on Success 

### ISSUE THREAD

**Issue by alexgwalley** [cqframework/clinical_quality_language#818]
In src/java/cql-to-elm-cli/src/main/java/org/cqframework/cql/cql2elm/cli/CqlTranslator.java:
all outputs are directed to standard error, making it impossible to check for actual errors (the program will always report failing even on success)

![image](https://user-images.githubusercontent.com/10475866/194600565-73d65270-e20b-426e-a514-8073e85f025a.png)

There are also other examples in this file where a similar issue occurs. I believe just changing every output which is not an error to System.out.println will fix the issue.

**Comment by JPercival** [comment]
This is actually correct behavior according to the POSIX guidelines. The actual output of the translator is the serialized ELM, which could be written to stdout (as opposed to a file) in order to pipe commands together. Sideband information is supposed to be written to stderr.

https://unix.stackexchange.com/questions/331611/do-progress-reports-logging-information-belong-on-stderr-or-stdout
