### ISSUE TITLE
Review/update the Java Quickstart

### ISSUE THREAD

**Issue by brynrhodes** [cqframework/clinical_quality_language#851]
Review and update the Readme and Java Quickstart.
The readme says Java 8, but since 2.0, the translator has required Java 11+.
FInd a way to dynamically set the version of the project in the readmes so that they don't get out of date when new releases happen

**Comment by ddieppois** [comment]
I'm not sure it's possible to dynamically update the readme.md especially since the sentence depend on an external link.

> To build the project, install the [Java SE Development
Kit 8](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html) (a.k.a. JDK 1.8)

We could set two variables at the very begining that refers to the 'URL' and 'VERSION' of JAVA and simply update those. We can refer those variables in the documentation whenever we need it.
